In [10]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

Leitura dos dados

In [11]:
#leitura com pandas
notas_selecao = pd.read_csv('data/enem19-sem_Zzero.csv')
notas_selecao

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_COR_RACA,TP_SEXO,NU_IDADE,TP_ENSINO,TP_ESCOLA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_MT,NU_NOTA_LC,NU_NOTA_REDACAO
0,190001004967,2019,1506807,Santarém,15,PA,3,F,20,1.0,1,537.9,582.2,417.7,585.7,780.0
1,190001005059,2019,1506807,Santarém,15,PA,4,F,17,1.0,2,416.2,569.5,459.9,539.6,660.0
2,190001005138,2019,1508100,Tucuruí,15,PA,3,M,19,NaN,1,526.9,589.7,708.5,588.7,860.0
3,190001005147,2019,1505205,Oeiras do Pará,15,PA,3,F,37,1.0,1,376.8,502.1,392.1,546.5,620.0
4,190001005219,2019,1502954,Eldorado do Carajás,15,PA,3,F,18,1.0,1,377.6,443.8,425.0,433.5,340.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31462,190006119878,2019,2610608,Paudalho,26,PE,0,F,19,1.0,1,419.4,354.0,587.7,461.2,520.0
31463,190006119928,2019,2700300,Arapiraca,27,AL,3,F,26,1.0,1,567.1,513.7,551.0,559.2,460.0
31464,190006120038,2019,2912103,Ibicaraí,29,BA,4,F,17,NaN,2,340.9,497.7,372.7,386.8,260.0
31465,190006120062,2019,2927408,Salvador,29,BA,3,F,18,1.0,2,397.6,438.5,450.2,476.9,300.0
31466,190006120091,2019,3155603,Rio Pardo de Minas,31,MG,3,M,17,1.0,2,459.8,439.3,448.7,509.6,440.0

Grafico de dispersao

In [12]:
disp = sns.barplot(data=notas_selecao, x="TP_SEXO", y="NU_NOOTA_MT")
disp

ValueError: Could not interpret input 'NU_NOOTA_MT'