In [1]:
import pandas as pd
import matplotlib as mpl
import seaborn as sns
import os
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('data/itens_2009.csv')
df

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA
0,46,CH,60181.0,A,NaN,0,NaN,0.70844,-0.23821,0.02167,AZUL,53
1,46,CH,60181.0,A,NaN,0,NaN,0.70844,-0.23821,0.02167,AMARELO,54
2,46,CH,60182.0,A,NaN,0,NaN,1.41931,0.48597,0.30167,BRANCO,55
3,46,CH,60185.0,A,NaN,0,NaN,1.40172,2.50064,0.26532,ROSA,56
4,46,CH,58938.0,B,NaN,0,NaN,2.21264,0.49351,0.16385,AZUL,69
...,...,...,...,...,...,...,...,...,...,...,...,...
1435,180,MT,60236.0,B,30.0,1,Não permitiu a convergência do algoritmo de es...,NaN,NaN,NaN,ROSA,64
1436,180,MT,59388.0,C,NaN,0,NaN,1.71404,3.26465,0.19063,AMARELO,77
1437,180,MT,58351.0,A,NaN,0,NaN,2.20914,3.02862,0.14764,CINZA,78
1438,180,MT,58974.0,E,NaN,0,NaN,0.90268,3.16950,0.18234,AZUL,79
1439,180,MT,59377.0,D,NaN,0,NaN,1.13373,3.27284,0.10427,ROSA,80