In [2]:
import pandas as pd
from util import load_sample

In [4]:
load_sample(2015,10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q041,Q042,Q043,Q044,Q045,Q046,Q047,Q048,Q049,Q050
38356,150006043395,2015,4,M,0.0,1,1,2,0,2,...,NaN,C,A,A,B,B,B,B,B,D
703,150000111611,2015,4,F,0.0,3,1,1,1,1,...,NaN,A,A,A,A,A,A,A,A,A
5280,150000756258,2015,4,F,0.0,3,1,1,2,1,...,NaN,A,A,A,A,A,A,A,A,A
18152,150002780078,2015,6,M,0.0,3,1,1,5,1,...,NaN,B,A,A,A,A,D,A,A,A
25396,150004024080,2015,9,M,0.0,3,1,1,5,1,...,NaN,A,A,A,A,A,A,A,B,A
9938,150001410825,2015,2,F,0.0,3,1,2,0,2,...,NaN,B,A,A,A,B,A,A,A,A
35967,150005913301,2015,13,F,1.0,3,1,1,8,1,...,4.0,A,A,A,B,A,A,A,A,D
22540,150003474007,2015,3,F,0.0,2,1,1,2,1,...,NaN,A,A,A,A,A,A,A,A,A
25375,150003957711,2015,4,F,0.0,2,1,1,3,1,...,5.0,A,A,A,A,A,A,A,A,A
34063,150005515265,2015,7,M,0.0,1,1,1,6,1,...,NaN,A,A,A,A,A,A,A,A,A

In [10]:
from util import item_stats

In [11]:
item_stats(2015,"MT")

,N,mean,sd,total.r,total.r_if_rm,alpha_if_rm,SG_AREA,TX_GABARITO,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,ano,TP_LINGUA,IN_ITEM_ADAPTADO,TP_VERSAO_DIGITAL
38545,10000,0.2349,0.423958,0.137130,0.050166,0.672215,MT,D,0,NaN,2.00377,3.51933,0.20374,2015,NaN,1.0,NaN
61391,10000,0.1995,0.399644,0.186676,0.105585,0.668576,MT,B,0,NaN,1.86527,2.44217,0.16755,2015,NaN,1.0,NaN
41659,10000,0.4944,0.499994,0.393249,0.300996,0.655070,MT,B,0,NaN,1.44654,-0.39957,0.20014,2015,NaN,1.0,NaN
32149,10000,0.2756,0.446838,0.189113,0.098327,0.669491,MT,B,0,NaN,1.17400,2.83932,0.24418,2015,NaN,1.0,NaN
81583,10000,0.2419,0.428255,0.232106,0.146293,0.666260,MT,A,0,NaN,1.33762,2.31697,0.20623,2015,NaN,1.0,NaN
33017,10000,0.3237,0.467910,0.406498,0.321367,0.654145,MT,D,0,NaN,1.58698,0.56570,0.15746,2015,NaN,0.0,NaN
82507,10000,0.1986,0.398966,0.169916,0.088636,0.669561,MT,C,0,NaN,1.45220,2.82021,0.18333,2015,NaN,1.0,NaN
26277,10000,0.3398,0.473665,0.382063,0.294176,0.655990,MT,A,0,NaN,2.15675,0.94349,0.17590,2015,NaN,0.0,NaN
28143,10000,0.3095,0.462311,0.430836,0.348523,0.652340,MT,D,0,NaN,2.84267,1.10396,0.19698,2015,NaN,1.0,NaN
49204,10000,0.1270,0.332990,0.086693,0.018132,0.672432,MT,A,0,NaN,3.46951,4.11405,0.12580,2015,NaN,1.0,NaN
15876,10000,0.1698,0.375476,0.188274,0.112197,0.668039,MT,E,0,NaN,1.74749,2.59319,0.14249,2015,NaN,0.0,NaN
82330,10000,0.2256,0.417998,0.207105,0.122705,0.667680,MT,A,0,NaN,1.66698,2.59975,0.20736,2015,NaN,1.0,NaN
24019,10000,0.2555,0.436164,0.315407,0.231208,0.660778,MT,E,0,NaN,1.03003,2.09956,0.17070,2015,NaN,0.0,NaN
15890,10000,0.1204,0.325445,0.018160,-0.048861,0.675456,MT,D,0,NaN,3.41203,3.87930,0.05419,2015,NaN,0.0,NaN
28088,10000,0.3354,0.472154,0.224711,0.129644,0.667639,MT,C,0,NaN,2.15388,2.04178,0.28781,2015,NaN,1.0,NaN
29167,10000,0.3324,0.471097,0.276117,0.183119,0.663901,MT,A,0,NaN,1.42194,1.80813,0.27450,2015,NaN,1.0,NaN
30755,10000,0.2854,0.451627,0.211797,0.120589,0.668073,MT,D,0,NaN,0.87277,2.82511,0.21108,2015,NaN,1.0,NaN
28904,10000,0.2114,0.408322,0.246765,0.165488,0.665041,MT,C,0,NaN,2.52928,2.33098,0.19899,2015,NaN,1.0,NaN
54184,10000,0.3672,0.482066,0.355319,0.264115,0.658056,MT,B,0,NaN,1.76806,1.06274,0.21458,2015,NaN,1.0,NaN
29359,10000,0.1412,0.348245,0.202484,0.132304,0.666884,MT,E,0,NaN,1.16472,3.02993,0.10360,2015,NaN,1.0,NaN
28646,10000,0.2381,0.425942,0.267102,0.182939,0.663939,MT,C,0,NaN,1.98262,2.01086,0.12481,2015,NaN,1.0,NaN
83917,10000,0.2448,0.429990,0.108902,0.020402,0.674174,MT,A,0,NaN,0.32005,6.36790,0.15202,2015,NaN,1.0,NaN
79233,10000,0.1039,0.305146,0.028209,-0.034672,0.674324,MT,A,0,NaN,1.49081,4.51720,0.09464,2015,NaN,1.0,NaN
27281,10000,0.1557,0.362589,0.338882,0.270316,0.659455,MT,E,0,NaN,2.81962,1.82360,0.11266,2015,NaN,0.0,NaN
28651,10000,0.1765,0.381264,0.325980,0.253173,0.660091,MT,D,0,NaN,1.62208,1.72592,0.10767,2015,NaN,1.0,NaN
28578,10000,0.3222,0.467342,0.277801,0.185638,0.663723,MT,A,0,NaN,1.98660,1.68438,0.27270,2015,NaN,1.0,NaN
37274,10000,0.2827,0.450334,0.275671,0.186880,0.663645,MT,C,0,NaN,1.74587,2.17499,0.30318,2015,NaN,1.0,NaN
28637,10000,0.2765,0.447289,0.259083,0.170277,0.664753,MT,C,0,NaN,2.89731,1.93082,0.19951,2015,NaN,1.0,NaN
40487,10000,0.2234,0.416545,0.343244,0.264302,0.658888,MT,C,0,NaN,1.63224,1.56733,0.11271,2015,NaN,0.0,NaN
81781,10000,0.1231,0.328568,0.067025,-0.000692,0.673255,MT,E,0,NaN,3.41610,4.31587,0.12228,2015,NaN,0.0,NaN
38852,10000,0.1177,0.322269,0.177419,0.112080,0.667841,MT,B,0,NaN,1.65509,2.78727,0.08102,2015,NaN,1.0,NaN
33076,10000,0.2106,0.407755,0.180824,0.097938,0.669099,MT,D,0,NaN,1.18579,2.81649,0.17915,2015,NaN,1.0,NaN
30365,10000,0.2070,0.405176,0.264625,0.184589,0.663894,MT,E,0,NaN,2.02151,2.54329,0.23534,2015,NaN,1.0,NaN
39817,10000,0.2742,0.446133,0.397774,0.316230,0.654959,MT,C,0,NaN,1.76491,1.26471,0.11821,2015,NaN,1.0,NaN
60361,10000,0.2110,0.408039,0.112059,0.028131,0.673250,MT,A,0,NaN,1.70587,3.19644,0.20825,2015,NaN,1.0,NaN
63152,10000,0.2355,0.424332,0.194554,0.108544,0.668605,MT,B,0,NaN,2.14018,2.40051,0.21976,2015,NaN,1.0,NaN
38013,10000,0.4121,0.492238,0.313775,0.218232,0.661350,MT,D,0,NaN,1.22540,0.80613,0.17857,2015,NaN,1.0,NaN
31374,10000,0.3493,0.476773,0.391294,0.303413,0.655271,MT,B,0,NaN,2.75038,1.06733,0.22876,2015,NaN,1.0,NaN
60078,10000,0.2097,0.407115,0.344405,0.267375,0.658843,MT,E,0,NaN,1.77201,1.70467,0.12269,2015,NaN,1.0,NaN
82955,10000,0.2167,0.412017,0.157664,0.073473,0.670614,MT,E,0,NaN,0.78524,3.80554,0.18310,2015,NaN,1.0,NaN
40302,10000,0.1666,0.372637,0.100261,0.023576,0.672841,MT,D,0,NaN,0.79707,5.35024,0.16493,2015,NaN,1.0,NaN
62901,10000,0.3967,0.489237,0.351258,0.258390,0.658403,MT,E,0,NaN,1.54884,0.96427,0.24491,2015,NaN,1.0,NaN
41816,10000,0.6074,0.488353,0.331067,0.237221,0.659970,MT,B,0,NaN,1.49174,-0.42299,0.19323,2015,NaN,1.0,NaN
39806,10000,0.1966,0.397447,0.264446,0.185971,0.663841,MT,C,0,NaN,2.62877,2.01353,0.11918,2015,NaN,1.0,NaN
14712,10000,0.5673,0.495475,0.362313,0.268886,0.657558,MT,C,0,NaN,1.06024,-0.23853,0.20527,2015,NaN,0.0,NaN

In [14]:
itens = item_stats(2015,"MT")
itens

,N,mean,sd,total.r,total.r_if_rm,alpha_if_rm,SG_AREA,TX_GABARITO,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,ano,TP_LINGUA,IN_ITEM_ADAPTADO,TP_VERSAO_DIGITAL
38545,10000,0.2331,0.422827,0.152126,0.066992,0.681554,MT,D,0,NaN,2.00377,3.51933,0.20374,2015,NaN,1.0,NaN
61391,10000,0.2016,0.401215,0.194719,0.114786,0.678566,MT,B,0,NaN,1.86527,2.44217,0.16755,2015,NaN,1.0,NaN
41659,10000,0.4919,0.499959,0.406220,0.316432,0.665131,MT,B,0,NaN,1.44654,-0.39957,0.20014,2015,NaN,1.0,NaN
32149,10000,0.2857,0.451770,0.197448,0.107314,0.679469,MT,B,0,NaN,1.17400,2.83932,0.24418,2015,NaN,1.0,NaN
81583,10000,0.2406,0.427469,0.226477,0.142045,0.677131,MT,A,0,NaN,1.33762,2.31697,0.20623,2015,NaN,1.0,NaN
33017,10000,0.3233,0.467760,0.419862,0.337114,0.664272,MT,D,0,NaN,1.58698,0.56570,0.15746,2015,NaN,0.0,NaN
82507,10000,0.1999,0.399945,0.167040,0.086812,0.680123,MT,C,0,NaN,1.45220,2.82021,0.18333,2015,NaN,1.0,NaN
26277,10000,0.3423,0.474503,0.380963,0.294300,0.667090,MT,A,0,NaN,2.15675,0.94349,0.17590,2015,NaN,0.0,NaN
28143,10000,0.3055,0.460642,0.438053,0.357956,0.663020,MT,D,0,NaN,2.84267,1.10396,0.19698,2015,NaN,1.0,NaN
49204,10000,0.1251,0.330849,0.078913,0.011841,0.682967,MT,A,0,NaN,3.46951,4.11405,0.12580,2015,NaN,1.0,NaN
15876,10000,0.1840,0.387504,0.178698,0.101213,0.679213,MT,E,0,NaN,1.74749,2.59319,0.14249,2015,NaN,0.0,NaN
82330,10000,0.2299,0.420789,0.188286,0.104238,0.679336,MT,A,0,NaN,1.66698,2.59975,0.20736,2015,NaN,1.0,NaN
24019,10000,0.2593,0.438272,0.314753,0.231487,0.671617,MT,E,0,NaN,1.03003,2.09956,0.17070,2015,NaN,0.0,NaN
15890,10000,0.1212,0.326376,0.027461,-0.038726,0.685167,MT,D,0,NaN,3.41203,3.87930,0.05419,2015,NaN,0.0,NaN
28088,10000,0.3375,0.472881,0.232392,0.138955,0.677615,MT,C,0,NaN,2.15388,2.04178,0.28781,2015,NaN,1.0,NaN
29167,10000,0.3316,0.470812,0.271632,0.180026,0.674865,MT,A,0,NaN,1.42194,1.80813,0.27450,2015,NaN,1.0,NaN
30755,10000,0.2824,0.450189,0.208032,0.118487,0.678746,MT,D,0,NaN,0.87277,2.82511,0.21108,2015,NaN,1.0,NaN
28904,10000,0.2066,0.404886,0.250540,0.171389,0.675362,MT,C,0,NaN,2.52928,2.33098,0.19899,2015,NaN,1.0,NaN
54184,10000,0.3694,0.482666,0.375780,0.287220,0.667470,MT,B,0,NaN,1.76806,1.06274,0.21458,2015,NaN,1.0,NaN
29359,10000,0.1354,0.342167,0.212817,0.145219,0.676793,MT,E,0,NaN,1.16472,3.02993,0.10360,2015,NaN,1.0,NaN
28646,10000,0.2373,0.425449,0.262383,0.179516,0.674868,MT,C,0,NaN,1.98262,2.01086,0.12481,2015,NaN,1.0,NaN
83917,10000,0.2505,0.433323,0.131311,0.043755,0.683111,MT,A,0,NaN,0.32005,6.36790,0.15202,2015,NaN,1.0,NaN
79233,10000,0.1100,0.312905,0.037185,-0.026292,0.684318,MT,A,0,NaN,1.49081,4.51720,0.09464,2015,NaN,1.0,NaN
27281,10000,0.1527,0.359716,0.342166,0.275415,0.670125,MT,E,0,NaN,2.81962,1.82360,0.11266,2015,NaN,0.0,NaN
28651,10000,0.1800,0.384207,0.304228,0.231126,0.672127,MT,D,0,NaN,1.62208,1.72592,0.10767,2015,NaN,1.0,NaN
28578,10000,0.3201,0.466538,0.278986,0.188535,0.674293,MT,A,0,NaN,1.98660,1.68438,0.27270,2015,NaN,1.0,NaN
37274,10000,0.2772,0.447638,0.280593,0.193983,0.673947,MT,C,0,NaN,1.74587,2.17499,0.30318,2015,NaN,1.0,NaN
28637,10000,0.2655,0.441621,0.262750,0.176657,0.675044,MT,C,0,NaN,2.89731,1.93082,0.19951,2015,NaN,1.0,NaN
40487,10000,0.2270,0.418914,0.365570,0.288635,0.668331,MT,C,0,NaN,1.63224,1.56733,0.11271,2015,NaN,0.0,NaN
81781,10000,0.1179,0.322506,0.079903,0.014532,0.682706,MT,E,0,NaN,3.41610,4.31587,0.12228,2015,NaN,0.0,NaN
38852,10000,0.1271,0.333102,0.192916,0.126721,0.677670,MT,B,0,NaN,1.65509,2.78727,0.08102,2015,NaN,1.0,NaN
33076,10000,0.2090,0.406615,0.185862,0.104641,0.679182,MT,D,0,NaN,1.18579,2.81649,0.17915,2015,NaN,1.0,NaN
30365,10000,0.2065,0.404814,0.264000,0.185313,0.674563,MT,E,0,NaN,2.02151,2.54329,0.23534,2015,NaN,1.0,NaN
39817,10000,0.2742,0.446133,0.409918,0.330520,0.665176,MT,C,0,NaN,1.76491,1.26471,0.11821,2015,NaN,1.0,NaN
60361,10000,0.2099,0.407257,0.112775,0.030348,0.683400,MT,A,0,NaN,1.70587,3.19644,0.20825,2015,NaN,1.0,NaN
63152,10000,0.2418,0.428195,0.192953,0.107504,0.679213,MT,B,0,NaN,2.14018,2.40051,0.21976,2015,NaN,1.0,NaN
38013,10000,0.3961,0.489110,0.339261,0.247262,0.670211,MT,D,0,NaN,1.22540,0.80613,0.17857,2015,NaN,1.0,NaN
31374,10000,0.3420,0.474403,0.408971,0.324205,0.665027,MT,B,0,NaN,2.75038,1.06733,0.22876,2015,NaN,1.0,NaN
60078,10000,0.2140,0.410147,0.353679,0.277794,0.669124,MT,E,0,NaN,1.77201,1.70467,0.12269,2015,NaN,1.0,NaN
82955,10000,0.2121,0.408816,0.129779,0.047203,0.682475,MT,E,0,NaN,0.78524,3.80554,0.18310,2015,NaN,1.0,NaN
40302,10000,0.1716,0.377051,0.099201,0.022828,0.683245,MT,D,0,NaN,0.79707,5.35024,0.16493,2015,NaN,1.0,NaN
62901,10000,0.3961,0.489110,0.355229,0.264154,0.669020,MT,E,0,NaN,1.54884,0.96427,0.24491,2015,NaN,1.0,NaN
41816,10000,0.5968,0.490565,0.331333,0.238611,0.670812,MT,B,0,NaN,1.49174,-0.42299,0.19323,2015,NaN,1.0,NaN
39806,10000,0.2027,0.402031,0.268505,0.190530,0.674273,MT,C,0,NaN,2.62877,2.01353,0.11918,2015,NaN,1.0,NaN
14712,10000,0.5678,0.495407,0.354323,0.261968,0.669121,MT,C,0,NaN,1.06024,-0.23853,0.20527,2015,NaN,0.0,NaN

In [17]:
itens.sort_values("total.r")

,N,mean,sd,total.r,total.r_if_rm,alpha_if_rm,SG_AREA,TX_GABARITO,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,ano,TP_LINGUA,IN_ITEM_ADAPTADO,TP_VERSAO_DIGITAL
15890,10000,0.1212,0.326376,0.027461,-0.038726,0.685167,MT,D,0,NaN,3.41203,3.87930,0.05419,2015,NaN,0.0,NaN
79233,10000,0.1100,0.312905,0.037185,-0.026292,0.684318,MT,A,0,NaN,1.49081,4.51720,0.09464,2015,NaN,1.0,NaN
49204,10000,0.1251,0.330849,0.078913,0.011841,0.682967,MT,A,0,NaN,3.46951,4.11405,0.12580,2015,NaN,1.0,NaN
81781,10000,0.1179,0.322506,0.079903,0.014532,0.682706,MT,E,0,NaN,3.41610,4.31587,0.12228,2015,NaN,0.0,NaN
40302,10000,0.1716,0.377051,0.099201,0.022828,0.683245,MT,D,0,NaN,0.79707,5.35024,0.16493,2015,NaN,1.0,NaN
60361,10000,0.2099,0.407257,0.112775,0.030348,0.683400,MT,A,0,NaN,1.70587,3.19644,0.20825,2015,NaN,1.0,NaN
82955,10000,0.2121,0.408816,0.129779,0.047203,0.682475,MT,E,0,NaN,0.78524,3.80554,0.18310,2015,NaN,1.0,NaN
83917,10000,0.2505,0.433323,0.131311,0.043755,0.683111,MT,A,0,NaN,0.32005,6.36790,0.15202,2015,NaN,1.0,NaN
38545,10000,0.2331,0.422827,0.152126,0.066992,0.681554,MT,D,0,NaN,2.00377,3.51933,0.20374,2015,NaN,1.0,NaN
82507,10000,0.1999,0.399945,0.167040,0.086812,0.680123,MT,C,0,NaN,1.45220,2.82021,0.18333,2015,NaN,1.0,NaN
15876,10000,0.1840,0.387504,0.178698,0.101213,0.679213,MT,E,0,NaN,1.74749,2.59319,0.14249,2015,NaN,0.0,NaN
33076,10000,0.2090,0.406615,0.185862,0.104641,0.679182,MT,D,0,NaN,1.18579,2.81649,0.17915,2015,NaN,1.0,NaN
82330,10000,0.2299,0.420789,0.188286,0.104238,0.679336,MT,A,0,NaN,1.66698,2.59975,0.20736,2015,NaN,1.0,NaN
38852,10000,0.1271,0.333102,0.192916,0.126721,0.677670,MT,B,0,NaN,1.65509,2.78727,0.08102,2015,NaN,1.0,NaN
63152,10000,0.2418,0.428195,0.192953,0.107504,0.679213,MT,B,0,NaN,2.14018,2.40051,0.21976,2015,NaN,1.0,NaN
61391,10000,0.2016,0.401215,0.194719,0.114786,0.678566,MT,B,0,NaN,1.86527,2.44217,0.16755,2015,NaN,1.0,NaN
32149,10000,0.2857,0.451770,0.197448,0.107314,0.679469,MT,B,0,NaN,1.17400,2.83932,0.24418,2015,NaN,1.0,NaN
30755,10000,0.2824,0.450189,0.208032,0.118487,0.678746,MT,D,0,NaN,0.87277,2.82511,0.21108,2015,NaN,1.0,NaN
29359,10000,0.1354,0.342167,0.212817,0.145219,0.676793,MT,E,0,NaN,1.16472,3.02993,0.10360,2015,NaN,1.0,NaN
81583,10000,0.2406,0.427469,0.226477,0.142045,0.677131,MT,A,0,NaN,1.33762,2.31697,0.20623,2015,NaN,1.0,NaN
28088,10000,0.3375,0.472881,0.232392,0.138955,0.677615,MT,C,0,NaN,2.15388,2.04178,0.28781,2015,NaN,1.0,NaN
28904,10000,0.2066,0.404886,0.250540,0.171389,0.675362,MT,C,0,NaN,2.52928,2.33098,0.19899,2015,NaN,1.0,NaN
28646,10000,0.2373,0.425449,0.262383,0.179516,0.674868,MT,C,0,NaN,1.98262,2.01086,0.12481,2015,NaN,1.0,NaN
28637,10000,0.2655,0.441621,0.262750,0.176657,0.675044,MT,C,0,NaN,2.89731,1.93082,0.19951,2015,NaN,1.0,NaN
30365,10000,0.2065,0.404814,0.264000,0.185313,0.674563,MT,E,0,NaN,2.02151,2.54329,0.23534,2015,NaN,1.0,NaN
39806,10000,0.2027,0.402031,0.268505,0.190530,0.674273,MT,C,0,NaN,2.62877,2.01353,0.11918,2015,NaN,1.0,NaN
29167,10000,0.3316,0.470812,0.271632,0.180026,0.674865,MT,A,0,NaN,1.42194,1.80813,0.27450,2015,NaN,1.0,NaN
28578,10000,0.3201,0.466538,0.278986,0.188535,0.674293,MT,A,0,NaN,1.98660,1.68438,0.27270,2015,NaN,1.0,NaN
37274,10000,0.2772,0.447638,0.280593,0.193983,0.673947,MT,C,0,NaN,1.74587,2.17499,0.30318,2015,NaN,1.0,NaN
28651,10000,0.1800,0.384207,0.304228,0.231126,0.672127,MT,D,0,NaN,1.62208,1.72592,0.10767,2015,NaN,1.0,NaN
24019,10000,0.2593,0.438272,0.314753,0.231487,0.671617,MT,E,0,NaN,1.03003,2.09956,0.17070,2015,NaN,0.0,NaN
41816,10000,0.5968,0.490565,0.331333,0.238611,0.670812,MT,B,0,NaN,1.49174,-0.42299,0.19323,2015,NaN,1.0,NaN
38013,10000,0.3961,0.489110,0.339261,0.247262,0.670211,MT,D,0,NaN,1.22540,0.80613,0.17857,2015,NaN,1.0,NaN
27281,10000,0.1527,0.359716,0.342166,0.275415,0.670125,MT,E,0,NaN,2.81962,1.82360,0.11266,2015,NaN,0.0,NaN
60078,10000,0.2140,0.410147,0.353679,0.277794,0.669124,MT,E,0,NaN,1.77201,1.70467,0.12269,2015,NaN,1.0,NaN
14712,10000,0.5678,0.495407,0.354323,0.261968,0.669121,MT,C,0,NaN,1.06024,-0.23853,0.20527,2015,NaN,0.0,NaN
62901,10000,0.3961,0.489110,0.355229,0.264154,0.669020,MT,E,0,NaN,1.54884,0.96427,0.24491,2015,NaN,1.0,NaN
40487,10000,0.2270,0.418914,0.365570,0.288635,0.668331,MT,C,0,NaN,1.63224,1.56733,0.11271,2015,NaN,0.0,NaN
54184,10000,0.3694,0.482666,0.375780,0.287220,0.667470,MT,B,0,NaN,1.76806,1.06274,0.21458,2015,NaN,1.0,NaN
26277,10000,0.3423,0.474503,0.380963,0.294300,0.667090,MT,A,0,NaN,2.15675,0.94349,0.17590,2015,NaN,0.0,NaN
41659,10000,0.4919,0.499959,0.406220,0.316432,0.665131,MT,B,0,NaN,1.44654,-0.39957,0.20014,2015,NaN,1.0,NaN
31374,10000,0.3420,0.474403,0.408971,0.324205,0.665027,MT,B,0,NaN,2.75038,1.06733,0.22876,2015,NaN,1.0,NaN
39817,10000,0.2742,0.446133,0.409918,0.330520,0.665176,MT,C,0,NaN,1.76491,1.26471,0.11821,2015,NaN,1.0,NaN
33017,10000,0.3233,0.467760,0.419862,0.337114,0.664272,MT,D,0,NaN,1.58698,0.56570,0.15746,2015,NaN,0.0,NaN
28143,10000,0.3055,0.460642,0.438053,0.357956,0.663020,MT,D,0,NaN,2.84267,1.10396,0.19698,2015,NaN,1.0,NaN

In [7]:
from util import  item_info_inep

In [21]:
 item_info_inep(item = "15890")

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,ano,TP_LINGUA,IN_ITEM_ADAPTADO,TP_VERSAO_DIGITAL
8162,172,MT,15890,D,28.0,0,NaN,3.41203,3.8793,0.05419,ROSA,246,2015,NaN,0.0,NaN
8163,168,MT,15890,D,28.0,0,NaN,3.41203,3.8793,0.05419,AZUL,245,2015,NaN,0.0,NaN
8164,156,MT,15890,D,28.0,0,NaN,3.41203,3.8793,0.05419,CINZA,244,2015,NaN,0.0,NaN
8165,149,MT,15890,D,28.0,0,NaN,3.41203,3.8793,0.05419,AMARELO,243,2015,NaN,0.0,NaN
8166,156,MT,15890,D,28.0,0,NaN,3.41203,3.8793,0.05419,CINZA,254,2015,NaN,1.0,NaN